server:
  port: 8762 # 该注册中心启动端口

eureka:
  instance:
    hostname: eureka-server-two #eureka服务端的示例
  client:
    register-with-eureka: false #false 标识不向注册中心注册自己
    fetch-registry: false # false 表示自己就是注册中心，维护服务实例即可，不需要去检索服务
    service-url:
      defaultZone: http://eureka-server-one:8761/eureka/ # 这里配置集群的地址，多个用逗号分开。注意端口，不是当前服务的端口。写除自己外的其他注册中心地址